### ISSUE TITLE
Game freezes on window focus change

### ISSUE THREAD

**Issue by miikkas** [tknuutin/greatlanding#1]
The game freezes (movement stops, keys stop responding) when changing focus to another window, by e.g. alt+tabbing. Only refreshing the page restores the functionality. I'm using 64-bit Firefox on Windows.

**Comment by tknuutin** [comment]
Something to do with the onfocus / onblur functionality. Intended functionality is to pause the game when window is not active. Will investigate, thanks.

**Comment by tknuutin** [comment]
Should be fixed by commit https://github.com/tknuutin/greatlanding/commit/61acc0903c9120ca00d360799310fab715095c0b. Thanks!
